default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: daniel
  password: postgres
 
development:
  <<: *default
  database: dfv_find_my_coffee_development
  
test:
  <<: *default
  database: dfv_find_my_coffee_test
 
production:
  <<: *default
  database: find_my_coffee_api_production
  username: find_my_coffee_api
  password: <%= ENV['FIND_MY_COFFEE_API_DATABASE_PASSWORD'] %>